# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PipelineScript\ui\pipelineToolQT.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 424)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.modelsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.modelsGroupBox.setGeometry(QtCore.QRect(10, 80, 751, 291))
        self.modelsGroupBox.setObjectName("modelsGroupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.modelsGroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 729, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.modelsWindowVerticleLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.modelsWindowVerticleLayout.setContentsMargins(0, 0, 0, 0)
        self.modelsWindowVerticleLayout.setObjectName("modelsWindowVerticleLayout")
        self.headerHorizontalLayout = QtWidgets.QHBoxLayout()
        self.headerHorizontalLayout.setObjectName("headerHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(182, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.headerHorizontalLayout.addItem(spacerItem)
        self.dirModelLocationLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dirModelLocationLabel.setObjectName("dirModelLocationLabel")
        self.headerHorizontalLayout.addWidget(self.dirModelLocationLabel)
        spacerItem1 = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.headerHorizontalLayout.addItem(spacerItem1)
        self.rootLocationLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rootLocationLabel.setObjectName("rootLocationLabel")
        self.headerHorizontalLayout.addWidget(self.rootLocationLabel)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerHorizontalLayout.addItem(spacerItem2)
        self.modelsWindowVerticleLayout.addLayout(self.headerHorizontalLayout)
        self.modelsVerticleLayout = QtWidgets.QVBoxLayout()
        self.modelsVerticleLayout.setObjectName("modelsVerticleLayout")
        self.modelsWindowVerticleLayout.addLayout(self.modelsVerticleLayout)
        spacerItem3 = QtWidgets.QSpacerItem(724, 91, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.modelsWindowVerticleLayout.addItem(spacerItem3)
        self.footerHorizontalLayout = QtWidgets.QHBoxLayout()
        self.footerHorizontalLayout.setObjectName("footerHorizontalLayout")
        self.newRowButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newRowButton.sizePolicy().hasHeightForWidth())
        self.newRowButton.setSizePolicy(sizePolicy)
        self.newRowButton.setObjectName("newRowButton")
        self.footerHorizontalLayout.addWidget(self.newRowButton)
        self.clearModels = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clearModels.setObjectName("clearModels")
        self.footerHorizontalLayout.addWidget(self.clearModels)
        self.footerHorizontalLayout.setStretch(0, 4)
        self.footerHorizontalLayout.setStretch(1, 1)
        self.modelsWindowVerticleLayout.addLayout(self.footerHorizontalLayout)
        self.projectGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.projectGroupBox.setGeometry(QtCore.QRect(10, 10, 501, 61))
        self.projectGroupBox.setObjectName("projectGroupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.projectGroupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 481, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.projectsGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.projectsGridLayout.setContentsMargins(0, 0, 0, 0)
        self.projectsGridLayout.setObjectName("projectsGridLayout")
        self.projectLoadButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.projectLoadButton.setObjectName("projectLoadButton")
        self.projectsGridLayout.addWidget(self.projectLoadButton, 1, 2, 1, 1)
        self.projectSaveButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.projectSaveButton.setObjectName("projectSaveButton")
        self.projectsGridLayout.addWidget(self.projectSaveButton, 1, 4, 1, 1)
        self.projectNameText = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.projectNameText.setText("")
        self.projectNameText.setPlaceholderText("")
        self.projectNameText.setObjectName("projectNameText")
        self.projectsGridLayout.addWidget(self.projectNameText, 1, 1, 1, 1)
        self.projectNameLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.projectsGridLayout.addWidget(self.projectNameLabel, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCreate_Model = QtWidgets.QMenu(self.menubar)
        self.menuCreate_Model.setObjectName("menuCreate_Model")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCreate_Model.menuAction())

        self.retranslateUi(MainWindow)
        self.projectLoadButton.clicked.connect(MainWindow.sLoadProject) # type: ignore
        self.projectSaveButton.clicked.connect(MainWindow.sSaveProject) # type: ignore
        self.newRowButton.clicked.connect(MainWindow.sNewRow) # type: ignore
        self.clearModels.clicked.connect(MainWindow.sClearAllModels) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pipeline Structure Tool"))
        self.modelsGroupBox.setTitle(_translate("MainWindow", "Directory Models"))
        self.dirModelLocationLabel.setText(_translate("MainWindow", "Model File"))
        self.rootLocationLabel.setText(_translate("MainWindow", "Root location"))
        self.newRowButton.setText(_translate("MainWindow", "New Directory Model"))
        self.clearModels.setText(_translate("MainWindow", "Clear rows"))
        self.projectGroupBox.setTitle(_translate("MainWindow", "Project"))
        self.projectLoadButton.setText(_translate("MainWindow", "Load"))
        self.projectSaveButton.setText(_translate("MainWindow", "Save"))
        self.projectNameLabel.setText(_translate("MainWindow", "Project Name"))
        self.menuFile.setTitle(_translate("MainWindow", "Generate"))
        self.menuCreate_Model.setTitle(_translate("MainWindow", "Create Model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
